name: easy
description: '一个新的 Flutter 项目。'
# 下面这行可以防止包被意外地使用 `flutter pub publish` 发布到 pub.dev。
# 这是私有包的推荐设置。
publish_to: 'none' # 如果你想发布到 pub.dev，请删除这一行

# 下面定义了应用程序的版本号和构建号。
# 版本号是由点分隔的三个数字，例如 1.2.43，
# 后面可以跟一个可选的构建号，用 + 分隔。
# 版本号和构建号都可以在 flutter build 时通过
# --build-name 和 --build-number 分别进行覆盖。
# 在 Android 中，build-name 用作 versionName，build-number 用作 versionCode。
# 更多关于 Android 版本控制的信息请参阅：https://developer.android.com/studio/publish/versioning
# 在 iOS 中，build-name 用作 CFBundleShortVersionString，build-number 用作 CFBundleVersion。
# 更多关于 iOS 版本控制的信息请参阅：
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 在 Windows 中，build-name 用作产品和文件版本的主版本号、次版本号和补丁版本，
# 而 build-number 用作构建后缀。
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# dependencies 指定了你的包需要依赖的其他包才能正常工作。
# 要自动将包依赖升级到最新版本，
# 可以考虑运行 `flutter pub upgrade --major-versions`。
# 或者，可以通过将下面的版本号手动更改为 pub.dev 上可用的最新版本来更新依赖。
# 要查看哪些依赖有更新的版本可用，请运行 `flutter pub outdated`。
dependencies:
  flutter:
    sdk: flutter

  # 下面这行将 Cupertino Icons 字体添加到你的应用程序中。
  # 与 CupertinoIcons 类一起使用，可以获取 iOS 风格的图标。
  cupertino_icons: ^1.0.8

  # 本地存储
  shared_preferences: ^2.3.4

  # 唯一 ID 生成
  uuid: ^4.5.1

  # 状态管理
  provider: ^6.1.2

  # 国际化日期格式
  intl: ^0.20.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下面的 "flutter_lints" 包包含一组推荐的 lint 规则，
  # 以鼓励良好的编码实践。该包提供的 lint 规则集
  # 在位于包根目录的 `analysis_options.yaml` 文件中激活。
  # 查看该文件以了解如何禁用特定的 lint 规则和启用其他规则。
  flutter_lints: ^5.0.0

# 有关此文件的通用 Dart 部分的信息，请参阅以下页面：
# https://dart.dev/tools/pub/pubspec

# 以下部分是 Flutter 包特有的配置。
flutter:
  # 下面这行确保 Material Icons 字体包含在你的应用程序中，
  # 这样你就可以在 material Icons 类中使用这些图标。
  uses-material-design: true

  # 要向应用程序添加静态资源，请添加一个 assets 部分，如下所示：
  assets:
    - assets/images/

  # 图片资源可以引用一个或多个特定分辨率的 "变体"，请参阅：
  # https://flutter.dev/to/resolution-aware-images

  # 有关从包依赖中添加静态资源的详细信息，请参阅：
  # https://flutter.dev/to/asset-from-package

  # 要向应用程序添加自定义字体，请在这个 "flutter" 部分中添加一个 fonts 部分。
  # 此列表中的每个条目都应该有一个带有字体系列名称的 "family" 键，
  # 以及一个 "fonts" 键，其中包含一个列表，给出字体的资源和其他描述符。
  # 例如：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关从包依赖中使用字体的详细信息，请参阅：
  # https://flutter.dev/to/font-from-package
